# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Hooks
#   Please note the hooks below are intended to be installed as a pre-push hook, e.g., specifying the --hook-type option:
#     pre-commit install --hook-type pre-push
# Hooks can and should be customized for personal and project-specific settings.
# Checkin to the repository should be aligned with the other service maintainers.
---
default_language_version:
  python: python3.12

default_stages: [pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        name: Ruff Linter & Formatter
        types_or: [python, pyi]
        args: ["--fix"]
      - id: ruff-format
        name: Ruff Linter & Formatter
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.2
    hooks:
      - id: uv-lock
      # keep the requirements.txt file updated
      - id: uv-export
      # Compile requirements
      - id: pip-compile
        args: [requirements-dev.in, -o, requirements-dev.txt]
        files: ^requirements-dev\.(in|txt)$
  # Use local hooks to tools installed via the environment-dev.yml.
  # This should allow making the installed tool without pre-commit, e.g., integrated in the IDE or manually.
  - repo: local
    hooks:
      - id: uv-pytoml-check
        name: UV Pytoml Check
        entry: uv pip check
        language: system
        types: [python]
        pass_filenames: false

      - id: uv-requirements-sync
        name: UV Sync Dependencies
        entry: uv pip compile pyproject.toml -o requirements.txt
        language: system
        types: [python]
        pass_filenames: false
