# Default configuration for Audio Transcription Pipeline
# This file contains all the default settings for the ASR system

# Directory paths - relative to project root
input_dir: "./inputs"
output_dir: "./outputs" 
cache_dir: "./cache"

# Audio processing settings
audio:
  sample_rate: 16000          # Target sample rate for processing
  batch_size: 8               # Batch size for processing multiple files
  max_duration: 30.0          # Maximum segment duration in seconds

# ASR transcription settings  
transcription:
  model_name: "stt_en_conformer_ctc_large"  # NVIDIA NeMo model name
  # Alternative models:
  # - "nvidia/parakeet-tdt-0.6b-v2"  # Faster transducer model (600M params)
  # - "stt_en_conformer_ctc_small"  # Smaller CTC model
  # - "stt_en_conformer_ctc_medium" # Medium CTC model
  device: "cuda"                            # Device for inference (cuda/cpu)
  enable_confidence_scores: true            # Include confidence scores
  language: "en"                           # Language code
  
  # Enhanced transcription options (optional)
  vocabulary_file: null                     # Path to custom vocabulary file
  beam_size: 4                             # Beam search width (1 = greedy)
  lm_weight: 0.0                           # Language model weight (0.0-2.0)
  word_insertion_penalty: 0.0              # Penalty for word insertions
  blank_penalty: 0.0                       # CTC blank penalty
  language_model_path: null                # Path to n-gram language model
  enable_file_context: true                # Enable per-file context loading

# Output formatting settings
output:
  formats: ["json", "txt", "attributed_txt"]  # Output formats to generate
  include_timestamps: true     # Include timing information
  include_confidence: true     # Include confidence scores in output
  pretty_json: true           # Format JSON with indentation

# Processing settings
processing:
  enable_caching: true        # Cache models and intermediate results
  parallel_workers: 1         # Number of parallel processing workers
  log_level: "INFO"          # Logging level (DEBUG, INFO, WARNING, ERROR)
  enable_diarization: true    # Enable speaker diarization