# NVIDIA NeMo Speaker Diarization Configuration
# Configuration for ClusteringDiarizer model

# Device configuration for model execution
device: "cuda"

# Audio processing parameters
sample_rate: 16000
num_workers: 4
batch_size: 1

diarizer:
  # Oracle VAD flag - required by NeMo ClusteringDiarizer
  oracle_vad: false
  
  # Manifest file path - will be set at runtime
  manifest_filepath: null
  
  # Speaker embedding model configuration
  speaker_embeddings:
    model_path: "titanet_large"
    parameters:
      window_length_in_sec: 1.5
      shift_length_in_sec: 0.75
      multiscale_weights: [1.0, 0.5, 0.25]
      
  # Voice Activity Detection model configuration
  vad:
    model_path: "vad_multilingual_marblenet"
    parameters:
      window_length_in_sec: 0.15
      shift_length_in_sec: 0.01
      
  # Clustering parameters
  clustering:
    parameters:
      oracle_num_speakers: false
      max_num_speakers: 8
      enhanced_count_thres: 0.8
      max_rp_threshold: 0.25
      sparse_search_volume: 30

  # Post-processing parameters
  postprocessing:
    overlap_infer_spk_limit: 5
    
  # Output directory (will be set at runtime)
  out_dir: null